name       : xwininfo
version    : 1.1.4
release    : 4
source     :
    - https://www.x.org/releases/individual/app/xwininfo-1.1.4.tar.gz : 3561f6c37eec416ad306f41ff24172b86cbed00854dff8912915e97d2cc17c34
license    :
    - MIT
component  : xorg.apps
summary    : X.Org Applications; xwininfo
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xcb-shape)
description: |
    X.Org Applications: xwininfo
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
