name        : xwininfo
version     : 1.1.2
release     : 2
source      :
    - http://xorg.freedesktop.org/releases/individual/app/xwininfo-1.1.2.tar.bz2 : 8fa66c9ce02da257613fa428137ab9efc89c8f9939c074513dbc0f407dc9ac3a
license     :
    - MIT
summary     : X.Org Applications; xwininfo
builddeps   :
    - pkgconfig(x11)
    - pkgconfig(xcb-shape)
description : |
    X.Org Applications: xwininfo
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
