name        : xwininfo
version     : 1.1.3
release     : 3
source     :
    - http://xorg.freedesktop.org/releases/individual/app/xwininfo-1.1.3.tar.bz2 : 218eb0ea95bd8de7903dfaa26423820c523ad1598be0751d2d8b6a2c23b23ff8
license     :
    - MIT
summary     : X.Org Applications; xwininfo
builddeps   :
    - pkgconfig(x11)
    - pkgconfig(xcb-shape)
description : |
    X.Org Applications: xwininfo
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
